name: Android CI

on:
    workflow_dispatch:
        inputs:
            build_number:
                description: 构建编号
                required: true
                default: 1
                type: number
            build_version:
                description: 版本号
                required: true
                default: 1.0.0
                type: string

jobs:
    build:
        name: 构建 Android APK
        runs-on: ubuntu-latest

        container:
            volumes:
                - /volume3/docker/service/data/gitea-runner/volumes/distribution:/opt/distribution:ro
                - /volume3/docker/service/data/gitea-runner/volumes/.android:/root/.android
                - /volume3/docker/service/data/gitea-runner/volumes/.gradle:/root/.gradle
                - /volume3/docker/service/data/gitea-runner/volumes/.m2:/root/.m2
            env:
                ANDROID_HOME: /root/.android/sdk

        steps:
            -   name: 检出代码
                uses: actions/checkout@v3
                with:
                    lfs: true

            -   name: 设置 JDK 21
                uses: actions/setup-java@v5
                with:
                    java-version: '21'
                    distribution: 'jdkfile'
                    jdkFile: /opt/distribution/OpenJDK21U-jdk_x64_linux_hotspot_21.0.9_10.tar.gz

            -   name: 授予 Gradle 执行权限
                run: chmod +x ./gradlew

            -   name: 构建 Release APK
                run: >
                    ./gradlew assembleRelease
                    -Dorg.gradle.daemon=false
                env:
                    BUILD_VERSION_CODE: ${{ github.event.inputs.build_number }}
                    BUILD_VERSION_NAME: ${{ github.event.inputs.build_version }}
                    BUILD_RELEASE_PASSWORD: ${{ secrets.BUILD_RELEASE_PASSWORD }}

            -   name: 上传 Release APK
                uses: actions/upload-artifact@v3
                with:
                    name: ObdChecker-Release
                    path: app/build/outputs/apk/release
